os:
  - linux
  - osx
language: generic
sudo: required
osx_image: xcode10.1
dist: trusty
env:
  - SWIFT_VERSION=4.0
  - SWIFT_VERSION=4.1
  - SWIFT_VERSION=4.2
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift test

